### ISSUE TITLE
Segmentation Fault on trying to send

### ISSUE THREAD

**Issue by shwetharmaiya** [ibillxia/xsmtp#5]
Once the server is up and a MAIL FROM:<bill@localhost.com> is sent. There is a core dump due to segmentation fault.  Below is the error:

ser@user-Lenovo-V110-15ISK:~/Downloads/xsmtp-master/xsmtp-master$ telnet localhost 25
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
220 Ready
HELO
250 OK
MAIL FROM<bill@localhost.com>
**Connection closed by foreign host.**

**Comment by ibillxia** [comment]
Did you edit the `conf.h` to set your own `data_dir ` ?
Please refer to the Usage in README

**Comment by shwetharmaiya** [comment]
I did so. It works now. I learnt a lot from the code. Thank you.
